// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: bridge/admin/v1/admin.proto

// The administration API of go-authn/bridge: what an operator asks a running
// provider, and the few things it may tell it to do. It is served only when
// the configuration has an admin block, on a unix socket or over mutual TLS.

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Started       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	Federation    *Federation            `protobuf:"bytes,4,opt,name=federation,proto3" json:"federation,omitempty"`
	Counts        *Counts                `protobuf:"bytes,5,opt,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *StatusResponse) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *StatusResponse) GetFederation() *Federation {
	if x != nil {
		return x.Federation
	}
	return nil
}

func (x *StatusResponse) GetCounts() *Counts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type Federation struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MetadataUrl string                 `protobuf:"bytes,1,opt,name=metadata_url,json=metadataUrl,proto3" json:"metadata_url,omitempty"`
	// idps is how many SAML 2.0 IdPs the metadata lists; usable those the
	// configuration lets people log in through.
	Idps        int32                  `protobuf:"varint,2,opt,name=idps,proto3" json:"idps,omitempty"`
	Usable      int32                  `protobuf:"varint,3,opt,name=usable,proto3" json:"usable,omitempty"`
	ValidUntil  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	LastRefresh *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_refresh,json=lastRefresh,proto3" json:"last_refresh,omitempty"`
	// last_error is the last refresh that failed, empty when the last one
	// succeeded.
	LastError     string `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Federation) Reset() {
	*x = Federation{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Federation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Federation) ProtoMessage() {}

func (x *Federation) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Federation.ProtoReflect.Descriptor instead.
func (*Federation) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *Federation) GetMetadataUrl() string {
	if x != nil {
		return x.MetadataUrl
	}
	return ""
}

func (x *Federation) GetIdps() int32 {
	if x != nil {
		return x.Idps
	}
	return 0
}

func (x *Federation) GetUsable() int32 {
	if x != nil {
		return x.Usable
	}
	return 0
}

func (x *Federation) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Federation) GetLastRefresh() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefresh
	}
	return nil
}

func (x *Federation) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Counts are what the provider holds in memory right now.
type Counts struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoginsInProgress int64                  `protobuf:"varint,1,opt,name=logins_in_progress,json=loginsInProgress,proto3" json:"logins_in_progress,omitempty"`
	Codes            int64                  `protobuf:"varint,2,opt,name=codes,proto3" json:"codes,omitempty"`
	DevicesWaiting   int64                  `protobuf:"varint,3,opt,name=devices_waiting,json=devicesWaiting,proto3" json:"devices_waiting,omitempty"`
	RefreshFamilies  int64                  `protobuf:"varint,4,opt,name=refresh_families,json=refreshFamilies,proto3" json:"refresh_families,omitempty"`
	AccessTokens     int64                  `protobuf:"varint,5,opt,name=access_tokens,json=accessTokens,proto3" json:"access_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Counts) Reset() {
	*x = Counts{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counts) ProtoMessage() {}

func (x *Counts) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counts.ProtoReflect.Descriptor instead.
func (*Counts) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Counts) GetLoginsInProgress() int64 {
	if x != nil {
		return x.LoginsInProgress
	}
	return 0
}

func (x *Counts) GetCodes() int64 {
	if x != nil {
		return x.Codes
	}
	return 0
}

func (x *Counts) GetDevicesWaiting() int64 {
	if x != nil {
		return x.DevicesWaiting
	}
	return 0
}

func (x *Counts) GetRefreshFamilies() int64 {
	if x != nil {
		return x.RefreshFamilies
	}
	return 0
}

func (x *Counts) GetAccessTokens() int64 {
	if x != nil {
		return x.AccessTokens
	}
	return 0
}

type RefreshMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataRequest) Reset() {
	*x = RefreshMetadataRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataRequest) ProtoMessage() {}

func (x *RefreshMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataRequest.ProtoReflect.Descriptor instead.
func (*RefreshMetadataRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

type ListIdPsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query matches display names, domains and entity IDs, as the
	// institution list's search does. Empty lists them all.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// limit bounds the answer; 0 is 100.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdPsRequest) Reset() {
	*x = ListIdPsRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdPsRequest) ProtoMessage() {}

func (x *ListIdPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdPsRequest.ProtoReflect.Descriptor instead.
func (*ListIdPsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListIdPsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListIdPsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type IdP struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityId   string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scopes     []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Categories []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	// allowed is whether the configuration lets people log in through it.
	Allowed       bool `protobuf:"varint,5,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdP) Reset() {
	*x = IdP{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdP) ProtoMessage() {}

func (x *IdP) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdP.ProtoReflect.Descriptor instead.
func (*IdP) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *IdP) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IdP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdP) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *IdP) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *IdP) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type ListIdPsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Idps  []*IdP                 `protobuf:"bytes,1,rep,name=idps,proto3" json:"idps,omitempty"`
	// total is how many matched, of which idps is the first limit.
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdPsResponse) Reset() {
	*x = ListIdPsResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdPsResponse) ProtoMessage() {}

func (x *ListIdPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdPsResponse.ProtoReflect.Descriptor instead.
func (*ListIdPsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListIdPsResponse) GetIdps() []*IdP {
	if x != nil {
		return x.Idps
	}
	return nil
}

func (x *ListIdPsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

type Client struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Public          bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Subject         string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience        []string               `protobuf:"bytes,5,rep,name=audience,proto3" json:"audience,omitempty"`
	Device          bool                   `protobuf:"varint,6,opt,name=device,proto3" json:"device,omitempty"`
	SshCertificates bool                   `protobuf:"varint,7,opt,name=ssh_certificates,json=sshCertificates,proto3" json:"ssh_certificates,omitempty"`
	AppPasswords    bool                   `protobuf:"varint,8,opt,name=app_passwords,json=appPasswords,proto3" json:"app_passwords,omitempty"`
	// refresh_lifetime_seconds is 0 when the client has no refresh tokens.
	RefreshLifetimeSeconds int64 `protobuf:"varint,9,opt,name=refresh_lifetime_seconds,json=refreshLifetimeSeconds,proto3" json:"refresh_lifetime_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Client) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Client) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *Client) GetDevice() bool {
	if x != nil {
		return x.Device
	}
	return false
}

func (x *Client) GetSshCertificates() bool {
	if x != nil {
		return x.SshCertificates
	}
	return false
}

func (x *Client) GetAppPasswords() bool {
	if x != nil {
		return x.AppPasswords
	}
	return false
}

func (x *Client) GetRefreshLifetimeSeconds() int64 {
	if x != nil {
		return x.RefreshLifetimeSeconds
	}
	return 0
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type RevokePersonRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the person's preferred_username (eppn by default), as the
	// tokens and certificates this provider issued name them.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePersonRequest) Reset() {
	*x = RevokePersonRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePersonRequest) ProtoMessage() {}

func (x *RevokePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePersonRequest.ProtoReflect.Descriptor instead.
func (*RevokePersonRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *RevokePersonRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RevokePersonResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefreshFamilies    int32                  `protobuf:"varint,1,opt,name=refresh_families,json=refreshFamilies,proto3" json:"refresh_families,omitempty"`
	AccessTokens       int32                  `protobuf:"varint,2,opt,name=access_tokens,json=accessTokens,proto3" json:"access_tokens,omitempty"`
	Logins             int32                  `protobuf:"varint,3,opt,name=logins,proto3" json:"logins,omitempty"`
	AppPasswordRemoved bool                   `protobuf:"varint,4,opt,name=app_password_removed,json=appPasswordRemoved,proto3" json:"app_password_removed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokePersonResponse) Reset() {
	*x = RevokePersonResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePersonResponse) ProtoMessage() {}

func (x *RevokePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePersonResponse.ProtoReflect.Descriptor instead.
func (*RevokePersonResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RevokePersonResponse) GetRefreshFamilies() int32 {
	if x != nil {
		return x.RefreshFamilies
	}
	return 0
}

func (x *RevokePersonResponse) GetAccessTokens() int32 {
	if x != nil {
		return x.AccessTokens
	}
	return 0
}

func (x *RevokePersonResponse) GetLogins() int32 {
	if x != nil {
		return x.Logins
	}
	return 0
}

func (x *RevokePersonResponse) GetAppPasswordRemoved() bool {
	if x != nil {
		return x.AppPasswordRemoved
	}
	return false
}

var File_bridge_admin_v1_admin_proto protoreflect.FileDescriptor

const file_bridge_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1bbridge/admin/v1/admin.proto\x12\x0fbridge.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStatusRequest\"\xe6\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x124\n" +
	"\astarted\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12;\n" +
	"\n" +
	"federation\x18\x04 \x01(\v2\x1b.bridge.admin.v1.FederationR\n" +
	"federation\x12/\n" +
	"\x06counts\x18\x05 \x01(\v2\x17.bridge.admin.v1.CountsR\x06counts\"\xf6\x01\n" +
	"\n" +
	"Federation\x12!\n" +
	"\fmetadata_url\x18\x01 \x01(\tR\vmetadataUrl\x12\x12\n" +
	"\x04idps\x18\x02 \x01(\x05R\x04idps\x12\x16\n" +
	"\x06usable\x18\x03 \x01(\x05R\x06usable\x12;\n" +
	"\vvalid_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12=\n" +
	"\flast_refresh\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRefresh\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"\xc5\x01\n" +
	"\x06Counts\x12,\n" +
	"\x12logins_in_progress\x18\x01 \x01(\x03R\x10loginsInProgress\x12\x14\n" +
	"\x05codes\x18\x02 \x01(\x03R\x05codes\x12'\n" +
	"\x0fdevices_waiting\x18\x03 \x01(\x03R\x0edevicesWaiting\x12)\n" +
	"\x10refresh_families\x18\x04 \x01(\x03R\x0frefreshFamilies\x12#\n" +
	"\raccess_tokens\x18\x05 \x01(\x03R\faccessTokens\"\x18\n" +
	"\x16RefreshMetadataRequest\"=\n" +
	"\x0fListIdPsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\x03IdP\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x18\n" +
	"\aallowed\x18\x05 \x01(\bR\aallowed\"R\n" +
	"\x10ListIdPsResponse\x12(\n" +
	"\x04idps\x18\x01 \x03(\v2\x14.bridge.admin.v1.IdPR\x04idps\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x14\n" +
	"\x12ListClientsRequest\"\x9c\x02\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x05 \x03(\tR\baudience\x12\x16\n" +
	"\x06device\x18\x06 \x01(\bR\x06device\x12)\n" +
	"\x10ssh_certificates\x18\a \x01(\bR\x0fsshCertificates\x12#\n" +
	"\rapp_passwords\x18\b \x01(\bR\fappPasswords\x128\n" +
	"\x18refresh_lifetime_seconds\x18\t \x01(\x03R\x16refreshLifetimeSeconds\"H\n" +
	"\x13ListClientsResponse\x121\n" +
	"\aclients\x18\x01 \x03(\v2\x17.bridge.admin.v1.ClientR\aclients\"1\n" +
	"\x13RevokePersonRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xb0\x01\n" +
	"\x14RevokePersonResponse\x12)\n" +
	"\x10refresh_families\x18\x01 \x01(\x05R\x0frefreshFamilies\x12#\n" +
	"\raccess_tokens\x18\x02 \x01(\x05R\faccessTokens\x12\x16\n" +
	"\x06logins\x18\x03 \x01(\x05R\x06logins\x120\n" +
	"\x14app_password_removed\x18\x04 \x01(\bR\x12appPasswordRemoved2\xb7\x03\n" +
	"\x05Admin\x12I\n" +
	"\x06Status\x12\x1e.bridge.admin.v1.StatusRequest\x1a\x1f.bridge.admin.v1.StatusResponse\x12[\n" +
	"\x0fRefreshMetadata\x12'.bridge.admin.v1.RefreshMetadataRequest\x1a\x1f.bridge.admin.v1.StatusResponse\x12O\n" +
	"\bListIdPs\x12 .bridge.admin.v1.ListIdPsRequest\x1a!.bridge.admin.v1.ListIdPsResponse\x12X\n" +
	"\vListClients\x12#.bridge.admin.v1.ListClientsRequest\x1a$.bridge.admin.v1.ListClientsResponse\x12[\n" +
	"\fRevokePerson\x12$.bridge.admin.v1.RevokePersonRequest\x1a%.bridge.admin.v1.RevokePersonResponseB:Z8github.com/go-authn/bridge/proto/bridge/admin/v1;adminv1b\x06proto3"

var (
	file_bridge_admin_v1_admin_proto_rawDescOnce sync.Once
	file_bridge_admin_v1_admin_proto_rawDescData []byte
)

func file_bridge_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_bridge_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_bridge_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_admin_v1_admin_proto_rawDesc), len(file_bridge_admin_v1_admin_proto_rawDesc)))
	})
	return file_bridge_admin_v1_admin_proto_rawDescData
}

var file_bridge_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bridge_admin_v1_admin_proto_goTypes = []any{
	(*StatusRequest)(nil),          // 0: bridge.admin.v1.StatusRequest
	(*StatusResponse)(nil),         // 1: bridge.admin.v1.StatusResponse
	(*Federation)(nil),             // 2: bridge.admin.v1.Federation
	(*Counts)(nil),                 // 3: bridge.admin.v1.Counts
	(*RefreshMetadataRequest)(nil), // 4: bridge.admin.v1.RefreshMetadataRequest
	(*ListIdPsRequest)(nil),        // 5: bridge.admin.v1.ListIdPsRequest
	(*IdP)(nil),                    // 6: bridge.admin.v1.IdP
	(*ListIdPsResponse)(nil),       // 7: bridge.admin.v1.ListIdPsResponse
	(*ListClientsRequest)(nil),     // 8: bridge.admin.v1.ListClientsRequest
	(*Client)(nil),                 // 9: bridge.admin.v1.Client
	(*ListClientsResponse)(nil),    // 10: bridge.admin.v1.ListClientsResponse
	(*RevokePersonRequest)(nil),    // 11: bridge.admin.v1.RevokePersonRequest
	(*RevokePersonResponse)(nil),   // 12: bridge.admin.v1.RevokePersonResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_bridge_admin_v1_admin_proto_depIdxs = []int32{
	13, // 0: bridge.admin.v1.StatusResponse.started:type_name -> google.protobuf.Timestamp
	2,  // 1: bridge.admin.v1.StatusResponse.federation:type_name -> bridge.admin.v1.Federation
	3,  // 2: bridge.admin.v1.StatusResponse.counts:type_name -> bridge.admin.v1.Counts
	13, // 3: bridge.admin.v1.Federation.valid_until:type_name -> google.protobuf.Timestamp
	13, // 4: bridge.admin.v1.Federation.last_refresh:type_name -> google.protobuf.Timestamp
	6,  // 5: bridge.admin.v1.ListIdPsResponse.idps:type_name -> bridge.admin.v1.IdP
	9,  // 6: bridge.admin.v1.ListClientsResponse.clients:type_name -> bridge.admin.v1.Client
	0,  // 7: bridge.admin.v1.Admin.Status:input_type -> bridge.admin.v1.StatusRequest
	4,  // 8: bridge.admin.v1.Admin.RefreshMetadata:input_type -> bridge.admin.v1.RefreshMetadataRequest
	5,  // 9: bridge.admin.v1.Admin.ListIdPs:input_type -> bridge.admin.v1.ListIdPsRequest
	8,  // 10: bridge.admin.v1.Admin.ListClients:input_type -> bridge.admin.v1.ListClientsRequest
	11, // 11: bridge.admin.v1.Admin.RevokePerson:input_type -> bridge.admin.v1.RevokePersonRequest
	1,  // 12: bridge.admin.v1.Admin.Status:output_type -> bridge.admin.v1.StatusResponse
	1,  // 13: bridge.admin.v1.Admin.RefreshMetadata:output_type -> bridge.admin.v1.StatusResponse
	7,  // 14: bridge.admin.v1.Admin.ListIdPs:output_type -> bridge.admin.v1.ListIdPsResponse
	10, // 15: bridge.admin.v1.Admin.ListClients:output_type -> bridge.admin.v1.ListClientsResponse
	12, // 16: bridge.admin.v1.Admin.RevokePerson:output_type -> bridge.admin.v1.RevokePersonResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bridge_admin_v1_admin_proto_init() }
func file_bridge_admin_v1_admin_proto_init() {
	if File_bridge_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_admin_v1_admin_proto_rawDesc), len(file_bridge_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_bridge_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_bridge_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_bridge_admin_v1_admin_proto = out.File
	file_bridge_admin_v1_admin_proto_goTypes = nil
	file_bridge_admin_v1_admin_proto_depIdxs = nil
}
