// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: bridge/admin/v1/admin.proto

// The administration API of go-authn/bridge: what an operator asks a running
// provider, and the few things it may tell it to do. It is served only when
// the configuration has an admin block, on a unix socket or over mutual TLS.

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the provider after the attempt: its federation says when the
	// metadata was last fetched, and last_error why this attempt failed.
	Status        *StatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataResponse) Reset() {
	*x = RefreshMetadataResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataResponse) ProtoMessage() {}

func (x *RefreshMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataResponse.ProtoReflect.Descriptor instead.
func (*RefreshMetadataResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshMetadataResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Started       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	Federation    *Federation            `protobuf:"bytes,4,opt,name=federation,proto3" json:"federation,omitempty"`
	Counts        *Counts                `protobuf:"bytes,5,opt,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *StatusResponse) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *StatusResponse) GetFederation() *Federation {
	if x != nil {
		return x.Federation
	}
	return nil
}

func (x *StatusResponse) GetCounts() *Counts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type Federation struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MetadataUrl string                 `protobuf:"bytes,1,opt,name=metadata_url,json=metadataUrl,proto3" json:"metadata_url,omitempty"`
	// idps is how many SAML 2.0 IdPs the metadata lists; usable those the
	// configuration lets people log in through.
	Idps        int32                  `protobuf:"varint,2,opt,name=idps,proto3" json:"idps,omitempty"`
	Usable      int32                  `protobuf:"varint,3,opt,name=usable,proto3" json:"usable,omitempty"`
	ValidUntil  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	LastRefresh *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_refresh,json=lastRefresh,proto3" json:"last_refresh,omitempty"`
	// last_error is the last refresh that failed, empty when the last one
	// succeeded.
	LastError     string `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Federation) Reset() {
	*x = Federation{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Federation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Federation) ProtoMessage() {}

func (x *Federation) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Federation.ProtoReflect.Descriptor instead.
func (*Federation) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Federation) GetMetadataUrl() string {
	if x != nil {
		return x.MetadataUrl
	}
	return ""
}

func (x *Federation) GetIdps() int32 {
	if x != nil {
		return x.Idps
	}
	return 0
}

func (x *Federation) GetUsable() int32 {
	if x != nil {
		return x.Usable
	}
	return 0
}

func (x *Federation) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Federation) GetLastRefresh() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefresh
	}
	return nil
}

func (x *Federation) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Counts are what the provider holds in memory right now.
type Counts struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoginsInProgress int64                  `protobuf:"varint,1,opt,name=logins_in_progress,json=loginsInProgress,proto3" json:"logins_in_progress,omitempty"`
	Codes            int64                  `protobuf:"varint,2,opt,name=codes,proto3" json:"codes,omitempty"`
	DevicesWaiting   int64                  `protobuf:"varint,3,opt,name=devices_waiting,json=devicesWaiting,proto3" json:"devices_waiting,omitempty"`
	RefreshFamilies  int64                  `protobuf:"varint,4,opt,name=refresh_families,json=refreshFamilies,proto3" json:"refresh_families,omitempty"`
	AccessTokens     int64                  `protobuf:"varint,5,opt,name=access_tokens,json=accessTokens,proto3" json:"access_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Counts) Reset() {
	*x = Counts{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counts) ProtoMessage() {}

func (x *Counts) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counts.ProtoReflect.Descriptor instead.
func (*Counts) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Counts) GetLoginsInProgress() int64 {
	if x != nil {
		return x.LoginsInProgress
	}
	return 0
}

func (x *Counts) GetCodes() int64 {
	if x != nil {
		return x.Codes
	}
	return 0
}

func (x *Counts) GetDevicesWaiting() int64 {
	if x != nil {
		return x.DevicesWaiting
	}
	return 0
}

func (x *Counts) GetRefreshFamilies() int64 {
	if x != nil {
		return x.RefreshFamilies
	}
	return 0
}

func (x *Counts) GetAccessTokens() int64 {
	if x != nil {
		return x.AccessTokens
	}
	return 0
}

type RefreshMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataRequest) Reset() {
	*x = RefreshMetadataRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataRequest) ProtoMessage() {}

func (x *RefreshMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataRequest.ProtoReflect.Descriptor instead.
func (*RefreshMetadataRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListIdPsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query matches display names, domains and entity IDs, as the
	// institution list's search does. Empty lists them all.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// limit bounds the answer; 0 is 100.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdPsRequest) Reset() {
	*x = ListIdPsRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdPsRequest) ProtoMessage() {}

func (x *ListIdPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdPsRequest.ProtoReflect.Descriptor instead.
func (*ListIdPsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListIdPsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListIdPsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type IdP struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityId   string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scopes     []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Categories []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	// allowed is whether people can log in through it: the configuration
	// lists it (or lists none) and it is not disabled.
	Allowed       bool `protobuf:"varint,5,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Disabled      bool `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdP) Reset() {
	*x = IdP{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdP) ProtoMessage() {}

func (x *IdP) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdP.ProtoReflect.Descriptor instead.
func (*IdP) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *IdP) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IdP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdP) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *IdP) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *IdP) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *IdP) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type ListIdPsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Idps  []*IdP                 `protobuf:"bytes,1,rep,name=idps,proto3" json:"idps,omitempty"`
	// total is how many matched, of which idps is the first limit.
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdPsResponse) Reset() {
	*x = ListIdPsResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdPsResponse) ProtoMessage() {}

func (x *ListIdPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdPsResponse.ProtoReflect.Descriptor instead.
func (*ListIdPsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListIdPsResponse) GetIdps() []*IdP {
	if x != nil {
		return x.Idps
	}
	return nil
}

func (x *ListIdPsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

type Client struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Public          bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Subject         string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience        []string               `protobuf:"bytes,5,rep,name=audience,proto3" json:"audience,omitempty"`
	Device          bool                   `protobuf:"varint,6,opt,name=device,proto3" json:"device,omitempty"`
	SshCertificates bool                   `protobuf:"varint,7,opt,name=ssh_certificates,json=sshCertificates,proto3" json:"ssh_certificates,omitempty"`
	AppPasswords    bool                   `protobuf:"varint,8,opt,name=app_passwords,json=appPasswords,proto3" json:"app_passwords,omitempty"`
	// refresh_lifetime_seconds is 0 when the client has no refresh tokens.
	RefreshLifetimeSeconds int64 `protobuf:"varint,9,opt,name=refresh_lifetime_seconds,json=refreshLifetimeSeconds,proto3" json:"refresh_lifetime_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Client) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Client) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *Client) GetDevice() bool {
	if x != nil {
		return x.Device
	}
	return false
}

func (x *Client) GetSshCertificates() bool {
	if x != nil {
		return x.SshCertificates
	}
	return false
}

func (x *Client) GetAppPasswords() bool {
	if x != nil {
		return x.AppPasswords
	}
	return false
}

func (x *Client) GetRefreshLifetimeSeconds() int64 {
	if x != nil {
		return x.RefreshLifetimeSeconds
	}
	return 0
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type RevokePersonRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the person's preferred_username (eppn by default), as the
	// tokens and certificates this provider issued name them.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePersonRequest) Reset() {
	*x = RevokePersonRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePersonRequest) ProtoMessage() {}

func (x *RevokePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePersonRequest.ProtoReflect.Descriptor instead.
func (*RevokePersonRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RevokePersonRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Revoked is what a revocation ended.
type Revoked struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefreshFamilies int32                  `protobuf:"varint,1,opt,name=refresh_families,json=refreshFamilies,proto3" json:"refresh_families,omitempty"`
	AccessTokens    int32                  `protobuf:"varint,2,opt,name=access_tokens,json=accessTokens,proto3" json:"access_tokens,omitempty"`
	// logins are logins and device grants in progress.
	Logins        int32 `protobuf:"varint,3,opt,name=logins,proto3" json:"logins,omitempty"`
	AppPasswords  int32 `protobuf:"varint,4,opt,name=app_passwords,json=appPasswords,proto3" json:"app_passwords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revoked) Reset() {
	*x = Revoked{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revoked) ProtoMessage() {}

func (x *Revoked) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revoked.ProtoReflect.Descriptor instead.
func (*Revoked) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *Revoked) GetRefreshFamilies() int32 {
	if x != nil {
		return x.RefreshFamilies
	}
	return 0
}

func (x *Revoked) GetAccessTokens() int32 {
	if x != nil {
		return x.AccessTokens
	}
	return 0
}

func (x *Revoked) GetLogins() int32 {
	if x != nil {
		return x.Logins
	}
	return 0
}

func (x *Revoked) GetAppPasswords() int32 {
	if x != nil {
		return x.AppPasswords
	}
	return 0
}

type RevokePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       *Revoked               `protobuf:"bytes,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePersonResponse) Reset() {
	*x = RevokePersonResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePersonResponse) ProtoMessage() {}

func (x *RevokePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePersonResponse.ProtoReflect.Descriptor instead.
func (*RevokePersonResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RevokePersonResponse) GetRevoked() *Revoked {
	if x != nil {
		return x.Revoked
	}
	return nil
}

// Disabled is one person or one institution this provider refuses.
type Disabled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of username and entity_id is set.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EntityId string `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason   string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// by is who disabled it: cn=<certificate CN> or uid=<peer uid>.
	By    string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	Since *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	// until is when it lapses; absent, never.
	Until         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disabled) Reset() {
	*x = Disabled{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disabled) ProtoMessage() {}

func (x *Disabled) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disabled.ProtoReflect.Descriptor instead.
func (*Disabled) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *Disabled) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Disabled) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Disabled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Disabled) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *Disabled) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Disabled) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type DisablePersonRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the person's preferred_username, as RevokePersonRequest.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// until is when it lapses; absent, it lasts until EnablePerson.
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePersonRequest) Reset() {
	*x = DisablePersonRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePersonRequest) ProtoMessage() {}

func (x *DisablePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePersonRequest.ProtoReflect.Descriptor instead.
func (*DisablePersonRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *DisablePersonRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DisablePersonRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisablePersonRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type DisablePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      *Disabled              `protobuf:"bytes,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Revoked       *Revoked               `protobuf:"bytes,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePersonResponse) Reset() {
	*x = DisablePersonResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePersonResponse) ProtoMessage() {}

func (x *DisablePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePersonResponse.ProtoReflect.Descriptor instead.
func (*DisablePersonResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *DisablePersonResponse) GetDisabled() *Disabled {
	if x != nil {
		return x.Disabled
	}
	return nil
}

func (x *DisablePersonResponse) GetRevoked() *Revoked {
	if x != nil {
		return x.Revoked
	}
	return nil
}

type EnablePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePersonRequest) Reset() {
	*x = EnablePersonRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePersonRequest) ProtoMessage() {}

func (x *EnablePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePersonRequest.ProtoReflect.Descriptor instead.
func (*EnablePersonRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *EnablePersonRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type EnablePersonResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// was_disabled is false when there was nothing to lift.
	WasDisabled   bool `protobuf:"varint,1,opt,name=was_disabled,json=wasDisabled,proto3" json:"was_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePersonResponse) Reset() {
	*x = EnablePersonResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePersonResponse) ProtoMessage() {}

func (x *EnablePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePersonResponse.ProtoReflect.Descriptor instead.
func (*EnablePersonResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *EnablePersonResponse) GetWasDisabled() bool {
	if x != nil {
		return x.WasDisabled
	}
	return false
}

type DisableIdPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableIdPRequest) Reset() {
	*x = DisableIdPRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableIdPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIdPRequest) ProtoMessage() {}

func (x *DisableIdPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIdPRequest.ProtoReflect.Descriptor instead.
func (*DisableIdPRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *DisableIdPRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DisableIdPRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisableIdPRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type DisableIdPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      *Disabled              `protobuf:"bytes,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Revoked       *Revoked               `protobuf:"bytes,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableIdPResponse) Reset() {
	*x = DisableIdPResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableIdPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIdPResponse) ProtoMessage() {}

func (x *DisableIdPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIdPResponse.ProtoReflect.Descriptor instead.
func (*DisableIdPResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *DisableIdPResponse) GetDisabled() *Disabled {
	if x != nil {
		return x.Disabled
	}
	return nil
}

func (x *DisableIdPResponse) GetRevoked() *Revoked {
	if x != nil {
		return x.Revoked
	}
	return nil
}

type EnableIdPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableIdPRequest) Reset() {
	*x = EnableIdPRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableIdPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIdPRequest) ProtoMessage() {}

func (x *EnableIdPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIdPRequest.ProtoReflect.Descriptor instead.
func (*EnableIdPRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *EnableIdPRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type EnableIdPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasDisabled   bool                   `protobuf:"varint,1,opt,name=was_disabled,json=wasDisabled,proto3" json:"was_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableIdPResponse) Reset() {
	*x = EnableIdPResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableIdPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIdPResponse) ProtoMessage() {}

func (x *EnableIdPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIdPResponse.ProtoReflect.Descriptor instead.
func (*EnableIdPResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *EnableIdPResponse) GetWasDisabled() bool {
	if x != nil {
		return x.WasDisabled
	}
	return false
}

type ListDisabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisabledRequest) Reset() {
	*x = ListDisabledRequest{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisabledRequest) ProtoMessage() {}

func (x *ListDisabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisabledRequest.ProtoReflect.Descriptor instead.
func (*ListDisabledRequest) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

type ListDisabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	People        []*Disabled            `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	Idps          []*Disabled            `protobuf:"bytes,2,rep,name=idps,proto3" json:"idps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisabledResponse) Reset() {
	*x = ListDisabledResponse{}
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisabledResponse) ProtoMessage() {}

func (x *ListDisabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisabledResponse.ProtoReflect.Descriptor instead.
func (*ListDisabledResponse) Descriptor() ([]byte, []int) {
	return file_bridge_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListDisabledResponse) GetPeople() []*Disabled {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *ListDisabledResponse) GetIdps() []*Disabled {
	if x != nil {
		return x.Idps
	}
	return nil
}

var File_bridge_admin_v1_admin_proto protoreflect.FileDescriptor

const file_bridge_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1bbridge/admin/v1/admin.proto\x12\x0fbridge.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStatusRequest\"R\n" +
	"\x17RefreshMetadataResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.bridge.admin.v1.StatusResponseR\x06status\"\xe6\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x124\n" +
	"\astarted\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12;\n" +
	"\n" +
	"federation\x18\x04 \x01(\v2\x1b.bridge.admin.v1.FederationR\n" +
	"federation\x12/\n" +
	"\x06counts\x18\x05 \x01(\v2\x17.bridge.admin.v1.CountsR\x06counts\"\xf6\x01\n" +
	"\n" +
	"Federation\x12!\n" +
	"\fmetadata_url\x18\x01 \x01(\tR\vmetadataUrl\x12\x12\n" +
	"\x04idps\x18\x02 \x01(\x05R\x04idps\x12\x16\n" +
	"\x06usable\x18\x03 \x01(\x05R\x06usable\x12;\n" +
	"\vvalid_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12=\n" +
	"\flast_refresh\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRefresh\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"\xc5\x01\n" +
	"\x06Counts\x12,\n" +
	"\x12logins_in_progress\x18\x01 \x01(\x03R\x10loginsInProgress\x12\x14\n" +
	"\x05codes\x18\x02 \x01(\x03R\x05codes\x12'\n" +
	"\x0fdevices_waiting\x18\x03 \x01(\x03R\x0edevicesWaiting\x12)\n" +
	"\x10refresh_families\x18\x04 \x01(\x03R\x0frefreshFamilies\x12#\n" +
	"\raccess_tokens\x18\x05 \x01(\x03R\faccessTokens\"\x18\n" +
	"\x16RefreshMetadataRequest\"=\n" +
	"\x0fListIdPsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa4\x01\n" +
	"\x03IdP\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x18\n" +
	"\aallowed\x18\x05 \x01(\bR\aallowed\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\"R\n" +
	"\x10ListIdPsResponse\x12(\n" +
	"\x04idps\x18\x01 \x03(\v2\x14.bridge.admin.v1.IdPR\x04idps\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x14\n" +
	"\x12ListClientsRequest\"\x9c\x02\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x05 \x03(\tR\baudience\x12\x16\n" +
	"\x06device\x18\x06 \x01(\bR\x06device\x12)\n" +
	"\x10ssh_certificates\x18\a \x01(\bR\x0fsshCertificates\x12#\n" +
	"\rapp_passwords\x18\b \x01(\bR\fappPasswords\x128\n" +
	"\x18refresh_lifetime_seconds\x18\t \x01(\x03R\x16refreshLifetimeSeconds\"H\n" +
	"\x13ListClientsResponse\x121\n" +
	"\aclients\x18\x01 \x03(\v2\x17.bridge.admin.v1.ClientR\aclients\"1\n" +
	"\x13RevokePersonRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x96\x01\n" +
	"\aRevoked\x12)\n" +
	"\x10refresh_families\x18\x01 \x01(\x05R\x0frefreshFamilies\x12#\n" +
	"\raccess_tokens\x18\x02 \x01(\x05R\faccessTokens\x12\x16\n" +
	"\x06logins\x18\x03 \x01(\x05R\x06logins\x12#\n" +
	"\rapp_passwords\x18\x04 \x01(\x05R\fappPasswords\"J\n" +
	"\x14RevokePersonResponse\x122\n" +
	"\arevoked\x18\x01 \x01(\v2\x18.bridge.admin.v1.RevokedR\arevoked\"\xcf\x01\n" +
	"\bDisabled\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"|\n" +
	"\x14DisablePersonRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\x82\x01\n" +
	"\x15DisablePersonResponse\x125\n" +
	"\bdisabled\x18\x01 \x01(\v2\x19.bridge.admin.v1.DisabledR\bdisabled\x122\n" +
	"\arevoked\x18\x02 \x01(\v2\x18.bridge.admin.v1.RevokedR\arevoked\"1\n" +
	"\x13EnablePersonRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"9\n" +
	"\x14EnablePersonResponse\x12!\n" +
	"\fwas_disabled\x18\x01 \x01(\bR\vwasDisabled\"z\n" +
	"\x11DisableIdPRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\x7f\n" +
	"\x12DisableIdPResponse\x125\n" +
	"\bdisabled\x18\x01 \x01(\v2\x19.bridge.admin.v1.DisabledR\bdisabled\x122\n" +
	"\arevoked\x18\x02 \x01(\v2\x18.bridge.admin.v1.RevokedR\arevoked\"/\n" +
	"\x10EnableIdPRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"6\n" +
	"\x11EnableIdPResponse\x12!\n" +
	"\fwas_disabled\x18\x01 \x01(\bR\vwasDisabled\"\x15\n" +
	"\x13ListDisabledRequest\"x\n" +
	"\x14ListDisabledResponse\x121\n" +
	"\x06people\x18\x01 \x03(\v2\x19.bridge.admin.v1.DisabledR\x06people\x12-\n" +
	"\x04idps\x18\x02 \x03(\v2\x19.bridge.admin.v1.DisabledR\x04idps2\x8c\a\n" +
	"\fAdminService\x12I\n" +
	"\x06Status\x12\x1e.bridge.admin.v1.StatusRequest\x1a\x1f.bridge.admin.v1.StatusResponse\x12d\n" +
	"\x0fRefreshMetadata\x12'.bridge.admin.v1.RefreshMetadataRequest\x1a(.bridge.admin.v1.RefreshMetadataResponse\x12O\n" +
	"\bListIdPs\x12 .bridge.admin.v1.ListIdPsRequest\x1a!.bridge.admin.v1.ListIdPsResponse\x12X\n" +
	"\vListClients\x12#.bridge.admin.v1.ListClientsRequest\x1a$.bridge.admin.v1.ListClientsResponse\x12[\n" +
	"\fRevokePerson\x12$.bridge.admin.v1.RevokePersonRequest\x1a%.bridge.admin.v1.RevokePersonResponse\x12^\n" +
	"\rDisablePerson\x12%.bridge.admin.v1.DisablePersonRequest\x1a&.bridge.admin.v1.DisablePersonResponse\x12[\n" +
	"\fEnablePerson\x12$.bridge.admin.v1.EnablePersonRequest\x1a%.bridge.admin.v1.EnablePersonResponse\x12U\n" +
	"\n" +
	"DisableIdP\x12\".bridge.admin.v1.DisableIdPRequest\x1a#.bridge.admin.v1.DisableIdPResponse\x12R\n" +
	"\tEnableIdP\x12!.bridge.admin.v1.EnableIdPRequest\x1a\".bridge.admin.v1.EnableIdPResponse\x12[\n" +
	"\fListDisabled\x12$.bridge.admin.v1.ListDisabledRequest\x1a%.bridge.admin.v1.ListDisabledResponseB:Z8github.com/go-authn/bridge/proto/bridge/admin/v1;adminv1b\x06proto3"

var (
	file_bridge_admin_v1_admin_proto_rawDescOnce sync.Once
	file_bridge_admin_v1_admin_proto_rawDescData []byte
)

func file_bridge_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_bridge_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_bridge_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_admin_v1_admin_proto_rawDesc), len(file_bridge_admin_v1_admin_proto_rawDesc)))
	})
	return file_bridge_admin_v1_admin_proto_rawDescData
}

var file_bridge_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_bridge_admin_v1_admin_proto_goTypes = []any{
	(*StatusRequest)(nil),           // 0: bridge.admin.v1.StatusRequest
	(*RefreshMetadataResponse)(nil), // 1: bridge.admin.v1.RefreshMetadataResponse
	(*StatusResponse)(nil),          // 2: bridge.admin.v1.StatusResponse
	(*Federation)(nil),              // 3: bridge.admin.v1.Federation
	(*Counts)(nil),                  // 4: bridge.admin.v1.Counts
	(*RefreshMetadataRequest)(nil),  // 5: bridge.admin.v1.RefreshMetadataRequest
	(*ListIdPsRequest)(nil),         // 6: bridge.admin.v1.ListIdPsRequest
	(*IdP)(nil),                     // 7: bridge.admin.v1.IdP
	(*ListIdPsResponse)(nil),        // 8: bridge.admin.v1.ListIdPsResponse
	(*ListClientsRequest)(nil),      // 9: bridge.admin.v1.ListClientsRequest
	(*Client)(nil),                  // 10: bridge.admin.v1.Client
	(*ListClientsResponse)(nil),     // 11: bridge.admin.v1.ListClientsResponse
	(*RevokePersonRequest)(nil),     // 12: bridge.admin.v1.RevokePersonRequest
	(*Revoked)(nil),                 // 13: bridge.admin.v1.Revoked
	(*RevokePersonResponse)(nil),    // 14: bridge.admin.v1.RevokePersonResponse
	(*Disabled)(nil),                // 15: bridge.admin.v1.Disabled
	(*DisablePersonRequest)(nil),    // 16: bridge.admin.v1.DisablePersonRequest
	(*DisablePersonResponse)(nil),   // 17: bridge.admin.v1.DisablePersonResponse
	(*EnablePersonRequest)(nil),     // 18: bridge.admin.v1.EnablePersonRequest
	(*EnablePersonResponse)(nil),    // 19: bridge.admin.v1.EnablePersonResponse
	(*DisableIdPRequest)(nil),       // 20: bridge.admin.v1.DisableIdPRequest
	(*DisableIdPResponse)(nil),      // 21: bridge.admin.v1.DisableIdPResponse
	(*EnableIdPRequest)(nil),        // 22: bridge.admin.v1.EnableIdPRequest
	(*EnableIdPResponse)(nil),       // 23: bridge.admin.v1.EnableIdPResponse
	(*ListDisabledRequest)(nil),     // 24: bridge.admin.v1.ListDisabledRequest
	(*ListDisabledResponse)(nil),    // 25: bridge.admin.v1.ListDisabledResponse
	(*timestamppb.Timestamp)(nil),   // 26: google.protobuf.Timestamp
}
var file_bridge_admin_v1_admin_proto_depIdxs = []int32{
	2,  // 0: bridge.admin.v1.RefreshMetadataResponse.status:type_name -> bridge.admin.v1.StatusResponse
	26, // 1: bridge.admin.v1.StatusResponse.started:type_name -> google.protobuf.Timestamp
	3,  // 2: bridge.admin.v1.StatusResponse.federation:type_name -> bridge.admin.v1.Federation
	4,  // 3: bridge.admin.v1.StatusResponse.counts:type_name -> bridge.admin.v1.Counts
	26, // 4: bridge.admin.v1.Federation.valid_until:type_name -> google.protobuf.Timestamp
	26, // 5: bridge.admin.v1.Federation.last_refresh:type_name -> google.protobuf.Timestamp
	7,  // 6: bridge.admin.v1.ListIdPsResponse.idps:type_name -> bridge.admin.v1.IdP
	10, // 7: bridge.admin.v1.ListClientsResponse.clients:type_name -> bridge.admin.v1.Client
	13, // 8: bridge.admin.v1.RevokePersonResponse.revoked:type_name -> bridge.admin.v1.Revoked
	26, // 9: bridge.admin.v1.Disabled.since:type_name -> google.protobuf.Timestamp
	26, // 10: bridge.admin.v1.Disabled.until:type_name -> google.protobuf.Timestamp
	26, // 11: bridge.admin.v1.DisablePersonRequest.until:type_name -> google.protobuf.Timestamp
	15, // 12: bridge.admin.v1.DisablePersonResponse.disabled:type_name -> bridge.admin.v1.Disabled
	13, // 13: bridge.admin.v1.DisablePersonResponse.revoked:type_name -> bridge.admin.v1.Revoked
	26, // 14: bridge.admin.v1.DisableIdPRequest.until:type_name -> google.protobuf.Timestamp
	15, // 15: bridge.admin.v1.DisableIdPResponse.disabled:type_name -> bridge.admin.v1.Disabled
	13, // 16: bridge.admin.v1.DisableIdPResponse.revoked:type_name -> bridge.admin.v1.Revoked
	15, // 17: bridge.admin.v1.ListDisabledResponse.people:type_name -> bridge.admin.v1.Disabled
	15, // 18: bridge.admin.v1.ListDisabledResponse.idps:type_name -> bridge.admin.v1.Disabled
	0,  // 19: bridge.admin.v1.AdminService.Status:input_type -> bridge.admin.v1.StatusRequest
	5,  // 20: bridge.admin.v1.AdminService.RefreshMetadata:input_type -> bridge.admin.v1.RefreshMetadataRequest
	6,  // 21: bridge.admin.v1.AdminService.ListIdPs:input_type -> bridge.admin.v1.ListIdPsRequest
	9,  // 22: bridge.admin.v1.AdminService.ListClients:input_type -> bridge.admin.v1.ListClientsRequest
	12, // 23: bridge.admin.v1.AdminService.RevokePerson:input_type -> bridge.admin.v1.RevokePersonRequest
	16, // 24: bridge.admin.v1.AdminService.DisablePerson:input_type -> bridge.admin.v1.DisablePersonRequest
	18, // 25: bridge.admin.v1.AdminService.EnablePerson:input_type -> bridge.admin.v1.EnablePersonRequest
	20, // 26: bridge.admin.v1.AdminService.DisableIdP:input_type -> bridge.admin.v1.DisableIdPRequest
	22, // 27: bridge.admin.v1.AdminService.EnableIdP:input_type -> bridge.admin.v1.EnableIdPRequest
	24, // 28: bridge.admin.v1.AdminService.ListDisabled:input_type -> bridge.admin.v1.ListDisabledRequest
	2,  // 29: bridge.admin.v1.AdminService.Status:output_type -> bridge.admin.v1.StatusResponse
	1,  // 30: bridge.admin.v1.AdminService.RefreshMetadata:output_type -> bridge.admin.v1.RefreshMetadataResponse
	8,  // 31: bridge.admin.v1.AdminService.ListIdPs:output_type -> bridge.admin.v1.ListIdPsResponse
	11, // 32: bridge.admin.v1.AdminService.ListClients:output_type -> bridge.admin.v1.ListClientsResponse
	14, // 33: bridge.admin.v1.AdminService.RevokePerson:output_type -> bridge.admin.v1.RevokePersonResponse
	17, // 34: bridge.admin.v1.AdminService.DisablePerson:output_type -> bridge.admin.v1.DisablePersonResponse
	19, // 35: bridge.admin.v1.AdminService.EnablePerson:output_type -> bridge.admin.v1.EnablePersonResponse
	21, // 36: bridge.admin.v1.AdminService.DisableIdP:output_type -> bridge.admin.v1.DisableIdPResponse
	23, // 37: bridge.admin.v1.AdminService.EnableIdP:output_type -> bridge.admin.v1.EnableIdPResponse
	25, // 38: bridge.admin.v1.AdminService.ListDisabled:output_type -> bridge.admin.v1.ListDisabledResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_bridge_admin_v1_admin_proto_init() }
func file_bridge_admin_v1_admin_proto_init() {
	if File_bridge_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_admin_v1_admin_proto_rawDesc), len(file_bridge_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_bridge_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_bridge_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_bridge_admin_v1_admin_proto = out.File
	file_bridge_admin_v1_admin_proto_goTypes = nil
	file_bridge_admin_v1_admin_proto_depIdxs = nil
}
