// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: bridge/admin/v1/admin.proto

// The administration API of go-authn/bridge: what an operator asks a running
// provider, and the few things it may tell it to do. It is served only when
// the configuration has an admin block, on a unix socket or over mutual TLS.

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_Status_FullMethodName          = "/bridge.admin.v1.Admin/Status"
	Admin_RefreshMetadata_FullMethodName = "/bridge.admin.v1.Admin/RefreshMetadata"
	Admin_ListIdPs_FullMethodName        = "/bridge.admin.v1.Admin/ListIdPs"
	Admin_ListClients_FullMethodName     = "/bridge.admin.v1.Admin/ListClients"
	Admin_RevokePerson_FullMethodName    = "/bridge.admin.v1.Admin/RevokePerson"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	// Status is what the provider is, and how it is doing.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// RefreshMetadata fetches the federation's metadata now, rather than at
	// the next scheduled refresh, and says how it went.
	RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ListIdPs lists the federation's identity providers, as the institution
	// list shows them.
	ListIdPs(ctx context.Context, in *ListIdPsRequest, opts ...grpc.CallOption) (*ListIdPsResponse, error)
	// ListClients lists the relying parties the configuration declares.
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	// RevokePerson ends everything this provider still holds for somebody:
	// their refresh token families, the access tokens those bought, their
	// logins and device grants in progress, and their application password.
	RevokePerson(ctx context.Context, in *RevokePersonRequest, opts ...grpc.CallOption) (*RevokePersonResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Admin_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Admin_RefreshMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListIdPs(ctx context.Context, in *ListIdPsRequest, opts ...grpc.CallOption) (*ListIdPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdPsResponse)
	err := c.cc.Invoke(ctx, Admin_ListIdPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, Admin_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RevokePerson(ctx context.Context, in *RevokePersonRequest, opts ...grpc.CallOption) (*RevokePersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokePersonResponse)
	err := c.cc.Invoke(ctx, Admin_RevokePerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	// Status is what the provider is, and how it is doing.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// RefreshMetadata fetches the federation's metadata now, rather than at
	// the next scheduled refresh, and says how it went.
	RefreshMetadata(context.Context, *RefreshMetadataRequest) (*StatusResponse, error)
	// ListIdPs lists the federation's identity providers, as the institution
	// list shows them.
	ListIdPs(context.Context, *ListIdPsRequest) (*ListIdPsResponse, error)
	// ListClients lists the relying parties the configuration declares.
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	// RevokePerson ends everything this provider still holds for somebody:
	// their refresh token families, the access tokens those bought, their
	// logins and device grants in progress, and their application password.
	RevokePerson(context.Context, *RevokePersonRequest) (*RevokePersonResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAdminServer) RefreshMetadata(context.Context, *RefreshMetadataRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshMetadata not implemented")
}
func (UnimplementedAdminServer) ListIdPs(context.Context, *ListIdPsRequest) (*ListIdPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdPs not implemented")
}
func (UnimplementedAdminServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedAdminServer) RevokePerson(context.Context, *RevokePersonRequest) (*RevokePersonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokePerson not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RefreshMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RefreshMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RefreshMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RefreshMetadata(ctx, req.(*RefreshMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListIdPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListIdPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListIdPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListIdPs(ctx, req.(*ListIdPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RevokePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RevokePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RevokePerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RevokePerson(ctx, req.(*RevokePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.admin.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Admin_Status_Handler,
		},
		{
			MethodName: "RefreshMetadata",
			Handler:    _Admin_RefreshMetadata_Handler,
		},
		{
			MethodName: "ListIdPs",
			Handler:    _Admin_ListIdPs_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _Admin_ListClients_Handler,
		},
		{
			MethodName: "RevokePerson",
			Handler:    _Admin_RevokePerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/admin/v1/admin.proto",
}
